name = "Engine Testing";
act = 1;
music = bgmMainMenu;
looppoint = 70623;
levelflags = LEVELFLAG_SKIPSCORECARD|LEVELFLAG_NOACT|LEVELFLAG_INFINITETIME|LEVELFLAG_NORELOAD|LEVELFLAG_INFINITELIVES;
levelstyle = STYLETYPE_ENGINE;
